// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2laaqPop7jYO23L6CtK6UomvK4qNJvE',
    appId: '1:309044368033:android:9652505fdb7ad114da96e0',
    messagingSenderId: '309044368033',
    projectId: 'taufiq-cozy',
    storageBucket: 'taufiq-cozy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyfS7DV-3VpckGWWCAyPwJB4ASnwDwo-s',
    appId: '1:309044368033:ios:2311d3f7a5dc3cd2da96e0',
    messagingSenderId: '309044368033',
    projectId: 'taufiq-cozy',
    storageBucket: 'taufiq-cozy.firebasestorage.app',
    iosBundleId: 'com.example.taufiqsejatiCozy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyfS7DV-3VpckGWWCAyPwJB4ASnwDwo-s',
    appId: '1:309044368033:ios:2311d3f7a5dc3cd2da96e0',
    messagingSenderId: '309044368033',
    projectId: 'taufiq-cozy',
    storageBucket: 'taufiq-cozy.firebasestorage.app',
    iosBundleId: 'com.example.taufiqsejatiCozy',
  );
}
